### PR TITLE
Add mermaid support for our mdbook

### PR DESCRIPTION
**Pull request by AgeManning**
## Issue Addressed

Just browsing our book and noticed we don't have mermaid support.

This adds support for mermaid diagrams, however I've had to mess with the workflow and I've not tested the new build.

This works locally, but it remains to be seen if this holds up in the CI

Clone of #53

### CODE REVIEW

**Review by jking-aus — DISMISSED** [review]
lgtm but confirm you want this merged to stable not unstable

**Comment by AgeManning** [comment]
Nope, thanks for the catch.

Fixed

**Review by jking-aus — COMMENTED** [review]
lgtm

**Review by jking-aus — APPROVED** [review]
lgtm

**Pull request merged**
